# This is a basic workflow to help you get started with Actions

name: realcode

# Controls when the workflow will run

on:
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          mkdir build
          mkdir checkpoint
          sudo docker run --name criu --rm -itd --privileged -v "$(pwd)/build:/build"  -v "$(pwd)/checkpoint:/checkpoint" fawazahmed0/centos-criu
          sudo docker exec --privileged -it criu docker run --name docubuild -d --privileged -v /build:/build  -v /checkpoint:/checkpoint fawazahmed0/quran-hadith-search-docusaurus
          

